{
 "title": "DS18B20 Temperature Matrix Heatmap 5x6",
 "tags": [
  "beehive monitoring",
  "ds18b20",
  "grafana",
  "kotori daq",
  "mqtt",
  "raspberry pi",
  "sensor network",
  "temperature matrix"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "6x5 ds18b20 SVG-Pixmap",
   "type": "marcuscalidus-svg-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mois_noho_sensors",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "6x5 ds18b20 SVG-Pixmap text",
   "type": "marcuscalidus-svg-panel",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "format": "short",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mois_noho_sensors",
     "query": "SELECT mean(*) FROM \"mois_noho_sensors\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "device=noho, site=mois",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "mean", "name": "temp-ir-8-8" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mois_noho_sensors",
     "query": "SELECT mean(\"temp-ir-8-8\") FROM \"default_test1_sensors\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flugloch linke Schmalseite. Sensor 1_1 oben links, 6_5 unten rechts.",
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 8 }
  },
  {
   "title": "device=noho, site=mois",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "mean", "name": "temp-ir-8-8" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mois_noho_sensors",
     "query": "SELECT mean(\"temp-ir-8-8\") FROM \"default_test1_sensors\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Temp Wetterstation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mois_yun_sensors",
     "select": [
      [
       { "params": [ "wb_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Notizen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 41, "w": 24, "x": 0, "y": 28 },
     "content": "die idee: wenn ich im winter eh dämmmaterial auf die bienenkiste packe, dann kann ich per in die dämmung gearbeiteter temperatursensoren auch gleich die wanderschaft der heiztraube aufzeichnen.\n\nso sieht die filzmatte mit den sensoren aus:\n![Image](https://www.euse.de/wp/wp-content/uploads/2023/11/20231107_013850.jpg)\n\nund so, wenn sie im einsatz ist:\n\n![Image](https://community.hiveeyes.org/uploads/default/optimized/2X/4/4592049b22f880c3af2bad7f3ea623fa85c93595_2_690x461.jpeg)\n\nblaue **verbinder** wie hier von poesel entdeckt:\nhttps://community.hiveeyes.org/t/open-hive-temperature-array/524/34\n\npi für **1wire** klarmachen:\nhttps://community.element14.com/products/raspberry-pi/raspberrypi_projects/b/blog/posts/multiple-ds18b20-temp-sensors-interfacing-with-raspberry-pi\n\nsensordaten **gemapped und geordnet** wie hier von clemens vorgemacht:\nhttps://community.hiveeyes.org/t/ds18b20-temperatur-sensoren-am-one-wire-bus-anordnen/1399\n\n\n>     /sys/bus/w1/devices/28-00000735a982 temp-ir-4-1\n>     /sys/bus/w1/devices/28-000007359dde temp-ir-4-2\n>     /sys/bus/w1/devices/28-000007364e78 temp-ir-4-3\n>     /sys/bus/w1/devices/28-6a39eb086461 temp-ir-4-4\n>     /sys/bus/w1/devices/28-0939ee086461 temp-ir-4-5\n>     /sys/bus/w1/devices/28-00000735b04d temp-ir-3-5\n>     /sys/bus/w1/devices/28-8a3fee086461 temp-ir-3-4\n>     /sys/bus/w1/devices/28-1843f4086461 temp-ir-3-3\n>     /sys/bus/w1/devices/28-faf8eb086461 temp-ir-3-2\n>     /sys/bus/w1/devices/28-000007351a12 temp-ir-3-1\n>     /sys/bus/w1/devices/28-00000743bda0 temp-ir-2-1\n>     /sys/bus/w1/devices/28-000007351f7f temp-ir-2-2\n>     /sys/bus/w1/devices/28-129fd7086461 temp-ir-2-3\n>     /sys/bus/w1/devices/28-69e3eb086461 temp-ir-2-4\n>     /sys/bus/w1/devices/28-00000735b39e temp-ir-2-5\n>     /sys/bus/w1/devices/28-a825eb086461 temp-ir-1-5\n>     /sys/bus/w1/devices/28-000007350e77 temp-ir-1-4\n>     /sys/bus/w1/devices/28-000007359c4f temp-ir-1-3\n>     /sys/bus/w1/devices/28-00000735c6d1 temp-ir-1-2\n>     /sys/bus/w1/devices/28-000007359257 temp-ir-1-1\n\n### Projekt und Dokumentation:\n\nhttps://github.com/hiveeyes/ds18b20-datalogger\n\ndie panels (svg, js) angepasst auf mein 4x5-format (prozentzahlen, adressierung der array-variablen).\n\ndaten laufen rein in die datenbank.\ndie panels sehen ungefähr so aus, wie sie aussehen sollen.\nsoweit wunderbar.\n\nskript von sleep(900) auf cron umgestellt, beachte virtualenv: https://stackoverflow.com/questions/3287038/cron-and-virtualenv\n\n\n### todo\n* offset der sensoren ermitteln, https://community.hiveeyes.org/t/temperatursensoren-justieren-kalibrieren/1744/2\n\n\n### appendix: how to delete sensor failure entries from db\n\n    root@elbanco:~# influx\n    Connected to http://localhost:8086 version 1.7.10\n    InfluxDB shell version: 1.7.10\n    > use hiveeyes_....\n\n    Using database hiveeyes_....\n    > show series\n\n    key\n    ---\n    mois_noho_sensors\n    ...\n    > SHOW FIELD KEYS FROM mois_noho_sensors\n\n    name: mois_noho_sensors\n    fieldKey    fieldType\n    --------    ---------\n    temp-ir-1-1 float\n    temp-ir-1-2 float\n    temp-ir-1-3 float\n    ...\n    temp-ir-4-5 float\n    > select \"temp-ir-1-2\" from mois_noho_sensors where \"temp-ir-1-2\" < -50\n\n    name: mois_noho_sensors\n    time                temp-ir-1-2\n    ----                -----------\n    1699396254643410035 -99\n    > delete from mois_noho_sensors where time = 1699396254643410035\n\n    > exit\n    root@elbanco:~# exit\n    logout\n    Connection to elbanco.hiveeyes.org closed.\n\n\n\n\n"
    }
   ]
  }
 ]
}